### ISSUE TITLE
How did you setup the forge decompWorkspace?

### ISSUE THREAD

**Issue by FirokOtaku** [MrSTOP/Minecraft-1.7.10-Forge-1614-Mod#1]
recently I'm trying to moving my code from mc1.10.2 to mc1.7.10-forge1614, but it always failed when building the forge enviroment.
how did you setup it up?
最近正在把mod从1.10.2的forge环境迁移到1.7.10的forge1614环境
但是总是构建环境失败
想请问下你是怎么构建的?

**Comment by MrSTOP** [comment]
你可能需要科学上网，好像构建时要用的有些网站国内是访问不了的。

**Comment by MrSTOP** [comment]
你可能需要科学上网，构建时有些网站国内好像是访问不了的。如果你需要的话，我可以把构建好的项目发给你。
